### ISSUE TITLE
SendKeys are throwing error in the FileInput

### ISSUE THREAD

**Issue by govindd06** [thomhurst/Selenium.PlaywrightDriver#46]
We are getting the following error when trying to send the values using SendKeys for the FileInput.

Code : SearchContext.FindElement(By.Id(_id)).SendKeys(value);

Message: 
OneTimeSetUp: System.Exception :    at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 228
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at TomLonghurst.Selenium.PlaywrightWebDriver.Extensions.TaskExtensions.Synchronously(Task task)
   at TomLonghurst.Selenium.PlaywrightWebDriver.PlaywrightWebElement.SendKeys(String text)
   at IFramework.Controls.DetailPage.Fields.FileInput.set_Value(String value) in C:\software\automation\Framework\Controls\DetailPage\Fields\FileInput.cs:line 33
   at DataSetup.PackageImportAndInstallDataSetup.BeforeTestRun(ITest testDetails) in C:\software\automation\DataSetup\PackageManager\PackageImportAndInstallDataSetup.cs:line 29
   at IDataSetup.DataSetupAttribute.ExecuteAction(ITest testDetails, ActionType actionType) in C:\software\automation\DataSetup\DataSetupAttribute.cs:line 96

  ----> Microsoft.Playwright.PlaywrightException : Error: Input of type "file" cannot be filled
Call log:
  - waiting for Locator("//div[@id='importWizard' and not(contains(@style,'display: none'))]/parent::div").First.Locator("#impInputPackageFile").First
  -   locator resolved to <input type="file" name="packageFile" id="impInputPackageFile"/>
  -   fill("C:\software\automation\bin\Debug\net6.0\Content\Packages\Syssettings(v1.0.0.0).ipack")
  - attempting fill action
  -   waiting for element to be visible, enabled and editable

Please map the API for SendKeys for FileInput.

Thanks in Advance.

**Comment by thomhurst** [comment]
Should work in v1.0.42

**Comment by govindd06** [comment]
Thanks Tom :)
